name: GitHub Actions demo
on:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Event triggered: ${{github.event_name}}"
          echo "Branch ${{github.ref}}"
      - uses: actions/checkout@v3.3.0
      - name: List files
        run: |
            echo "Current repo name: ${{github.repository}}"
            tree
    
